language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq geoip-database
  - sudo apt-get install -qq python-lxml
  - export PIP_USE_MIRRORS=true
  - export DJANGO_SETTINGS_MODULE=proxylist.test_settings
install:
  - pip install -e .
  - pip install -r requirements/tests.txt Django==$DJANGO
  - sh -c "if [ '$SOUTH' = '1' ]; then pip install South==0.7.6; fi"
before_script:
  - flake8 --exclude=migrations proxylist
script:
  - coverage run --branch --source=proxylist `which django-admin.py` test proxylist
  - coverage report --omit="proxylist/test*"
env:
  - DJANGO=1.3.7 SOUTH=0
  - DJANGO=1.4.5 SOUTH=0
  - DJANGO=1.5.1 SOUTH=0
  - DJANGO=1.4.5 SOUTH=1
  - DJANGO=1.5.1 SOUTH=1
branches:
  only:
    - master

matrix:
  include:
   - python: 3.2
     env: DJANGO=Django==1.5.1 SOUTH=0
   - python: 3.3
     env: DJANGO=Django==1.5.1 SOUTH=0

after_success: coveralls
