language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq geoip-database
  - sudo apt-get install -qq python-lxml
  - export PIP_USE_MIRRORS=true
  - export DJANGO_SETTINGS_MODULE=proxylist.test_settings
install:
  - pip install -e .
  - pip install -r requirements/tests.txt Django==$DJANGO
before_script:
  - flake8 proxylist
script:
  - coverage run --branch --source=proxylist `which django-admin.py` test proxylist
  - coverage report --omit="proxylist/test*"
env:
  - DJANGO=1.3.7
  - DJANGO=1.4.5
  - DJANGO=1.5.1
branches:
  only:
    - master
